export const DEMO_CAMPAIGNS = [
  {
    id: "camp-001",
    name: "[DEMO] Urban Mobility 2026 - PK Sedan X Launch",
    code: "PK-UM-2026",
    status: "ACTIVE",
    objective: "สร้างยอดจองและทดลองขับกลุ่มคนทำงานรุ่นใหม่ (First-Jobber & Young Pro)",
    budget: 850000,
    start_date: "2026-09-01",
    end_date: "2026-10-31",
    target_audience: "คนเมือง อายุ 25-35 ปี ชื่นชอบดีไซน์ล้ำสมัย เทคโนโลยีประหยัดพลังงาน",
    key_message: "นิยามใหม่แห่งการขับขี่ในเมือง: คล่องตัว ปลอดภัย ประหยัดพลังงานระดับพรีเมียม",
  },
  {
    id: "camp-002",
    name: "[DEMO] PK EV HyperDrive - Safe Travel Campaign",
    code: "PK-EV-SAFE",
    status: "ACTIVE",
    objective: "โปรโมทระบบความปลอดภัย PK Pilot 3.0 และสมรรถนะการชาร์จไว",
    budget: 1200000,
    start_date: "2026-08-15",
    end_date: "2026-09-30",
    target_audience: "กลุ่มครอบครัวรุ่นใหม่ที่ใส่ใจความปลอดภัยระดับสูงสุด",
    key_message: "ปลอดภัยทุกมิติ เดินทางไกลไร้กังวลกับ PK Pilot 3.0",
  },
  {
    id: "camp-003",
    name: "[DEMO] PK Aftersales Freedom Service",
    code: "PK-AFTER-26",
    status: "ACTIVE",
    objective: "สร้างความเชื่อมั่นในการบริการหลังการขายและการรับประกันแบตเตอรี่ 8 ปี",
    budget: 450000,
    start_date: "2026-09-01",
    end_date: "2026-12-31",
    target_audience: "เจ้าของรถยนต์ PK ปัจจุบันและผู้ที่กำลังตัดสินใจซื้อ",
    key_message: "ดูแลไร้กังวล 8 ปีเต็ม มั่นใจทุกศูนย์บริการทั่วประเทศ",
  },
  {
    id: "camp-004",
    name: "[DEMO] PK Hybrid Performance Challenge",
    code: "PK-HYBRID-CHALLENGE",
    status: "DRAFT",
    objective: "ท้าพิสูจน์อัตราประหยัดน้ำมัน 28 กม./ลิตร กรุงเทพฯ - เชียงใหม่ ถังเดียวจบ",
    budget: 650000,
    start_date: "2026-10-01",
    end_date: "2026-11-15",
    target_audience: "สายท่องเที่ยว Road Trip และผู้ที่มองหาความประหยัดขั้นสุด",
    key_message: "ขับไกล ถังเดียวถึง คุ้มค่าทุกกิโลเมตร",
  },
  {
    id: "camp-005",
    name: "[DEMO] PK Fleet Corporate Solutions",
    code: "PK-FLEET-2026",
    status: "ACTIVE",
    objective: "ขยายฐานลูกค้านิติบุคคล องค์กร และรถประจำตำแหน่งผู้บริหาร",
    budget: 500000,
    start_date: "2026-07-01",
    end_date: "2026-12-31",
    target_audience: "ผู้บริหารฝ่ายจัดซื้อและผู้ประกอบการ SME / Corporate",
    key_message: "บริหารต้นทุนยานพาหนะอย่างคุ้มค่า ลดหย่อนภาษีได้สูงสุด",
  },
];
