import { ContentIdea } from "@/types";

export const DEMO_IDEAS: ContentIdea[] = [
  {
    id: "idea-001",
    campaign_id: "camp-001",
    title: "[DEMO] เงินเดือน 35,000 ขับ PK Sedan X ได้ไหม? เจาะค่าใช้จ่ายจริง",
    concept: "Infographic breakdown ค่าผ่อน ค่าน้ำมัน ค่าบำรุงรักษาต่อเดือน",
    hook: "เงินเดือน 35K แต่อยากขับ Sedan ไฮบริดตัวจบ... ไหวไหม? มาดูตัวเลขจริงกัน",
    target_audience: "พนักงานออฟฟิศ First Jobber ถึง Mid-level ที่กำลังวางแผนซื้อรถคันแรก",
    objective: "ลดความกังวลด้านการเงิน และกระตุ้น Leads ขอใบเสนอราคา",
    content_pillar: "Financial & Value Proof",
    platform: "facebook",
    format: "Carousel / Album Infographic",
    key_message: "ค่างวดเริ่มต้นวันละ 300 บาท ประหยัดน้ำมันกิโลละไม่ถึง 1.4 บาท",
    cta: "กดดาวน์โหลดตารางผ่อนและคำนวณสินเชื่อฟรีที่ลิงก์ในคอมเมนต์",
    reasoning: "ช่วยตอบข้อโต้แย้งหลักเรื่องภาระค่าใช้จ่าย ด้วยตรรกะความคุ้มค่าทางการเงิน",
    priority: "HIGH",
    funnel_stage: "MOFU",
    status: "APPROVED",
    created_at: "2026-09-02T10:00:00Z",
    updated_at: "2026-09-02T10:00:00Z",
  },
  {
    id: "idea-002",
    campaign_id: "camp-001",
    title: "[DEMO] 3 ฟังก์ชันใน PK Sedan X ที่คนขับรถติดใน กทม. จะตกหลุมรัก",
    concept: "POV วิดีโอสั้นจำลองสถานการณ์รถติดบนถนนสาทรชั่วโมงเร่งด่วน",
    hook: "ถ้าคุณต้องติดไฟแดงวันละ 2 ชั่วโมง... นี่คือ 3 ปุ่มที่คุณจะกดขอบคุณวิศวกรทุกวัน",
    target_audience: "คนทำงานในเมืองใหญ่ที่ต้องเผชิญปัญหารถติดทุกวัน",
    objective: "สร้าง Emotional Connection และยอด Engagement สูงใน TikTok",
    content_pillar: "Product Experience / Lifestyle",
    platform: "tiktok",
    format: "POV Short Video 45s",
    key_message: "Auto Brake Hold นุ่มนวล, แอร์ฟอกอากาศ PM2.5, และเบาะนวดผ่อนคลาย",
    cta: "ใครเจอปัญหานี้บ้าง? คอมเมนต์บอกพิกัดรถติดของคุณเลย",
    reasoning: "จับ Pain Point ยอดฮิตของคนเมือง ทำให้คอนเทนต์เข้าถึงง่าย",
    priority: "HIGH",
    funnel_stage: "TOFU",
    status: "AI_GENERATED",
    created_at: "2026-09-03T09:30:00Z",
    updated_at: "2026-09-03T09:30:00Z",
  },
  {
    id: "idea-003",
    campaign_id: "camp-001",
    title: "[DEMO] ทดสอบจริง! กรุงเทพฯ - พัทยา น้ำมันถังเดียวเหลือแค่ไหน?",
    concept: "Real-world Fuel Economy Challenge สไตล์ Creator Review โปร่งใส",
    hook: "ท้าพิสูจน์ตัวเลข 26.5 กม./ลิตร! ขับจริง เปิดแอร์ฉ่ำ 23 องศา คนนั่ง 4 คน จะรอดไหม?",
    target_audience: "กลุ่มคนที่มองหาความประหยัดจริง ไม่เชื่อเพียงตัวเลขในโบรชัวร์",
    objective: "สร้างความน่าเชื่อถือผ่านการทดสอบแบบ Real-World",
    content_pillar: "Real Proof & Performance",
    platform: "youtube",
    format: "Long-form Review 10 mins",
    key_message: "ตัวเลขจริงที่พิสูจน์ได้ สมรรถนะแรงแต่นุ่มนวล ไม่กินน้ำมันเกินจริง",
    cta: "ลงทะเบียนทดลองขับสัมผัสความประหยัดด้วยตัวคุณเองที่โชว์รูมใกล้บ้าน",
    reasoning: "ตอบสนองผู้บริโภคสายวิเคราะห์ที่ต้องการหลักฐานเชิงประจักษ์",
    priority: "HIGH",
    funnel_stage: "BOFU",
    status: "IN_REVIEW",
    created_at: "2026-09-04T11:15:00Z",
    updated_at: "2026-09-04T11:15:00Z",
  },
  {
    id: "idea-004",
    campaign_id: "camp-002",
    title: "[DEMO] ระบบช่วยเบรกฉุกเฉินทำงานยังไงเมื่อมีมอเตอร์ไซค์ตัดหน้า?",
    concept: "3D Animation จำลองการทำงานของ Radar & กล้องตรวจจับในเสี้ยววินาที",
    hook: "เสี้ยววินาทีแห่งชีวิต! เซนเซอร์หน้ารถมองเห็นอะไรก่อนสายตามนุษย์?",
    target_audience: "พ่อแม่และผู้ขับขี่ที่ให้ความสำคัญกับความปลอดภัยครอบครัว",
    objective: "Highlight เทคโนโลยีความปลอดภัย PK Pilot 3.0",
    content_pillar: "Technology & Safety",
    platform: "facebook",
    format: "Explainer Video 60s",
    key_message: "ระบบหยุดรถอัตโนมัติ ตอบสนองเร็วกว่ามนุษย์ 0.3 วินาที ป้องกันอุบัติเหตุได้จริง",
    cta: "คลิกอ่านผลทดสอบความปลอดภัยระดับ 5 ดาวจาก ASEAN NCAP",
    reasoning: "สร้างภาพลักษณ์ด้านวิศวกรรมความปลอดภัยชั้นนำ",
    priority: "MEDIUM",
    funnel_stage: "MOFU",
    status: "IDEA",
    created_at: "2026-09-04T14:00:00Z",
    updated_at: "2026-09-04T14:00:00Z",
  },
  {
    id: "idea-005",
    campaign_id: "camp-001",
    title: "[DEMO] เทียบชัดๆ: PK Sedan X vs คู่แข่งในพิกัดล้านต้น คันไหนให้อะไรมากกว่า?",
    concept: "ตารางเปรียบเทียบสเปกแบบหมัดต่อหมัด ด้านแรงม้า ฟังก์ชัน และพื้นที่โดยสาร",
    hook: "กำเงินล้านนึง ซื้อรุ่นไหนคุ้มสุดปี 2026? เทียบจุดต่อจุดไม่มีกั๊ก",
    target_audience: "กลุ่มผู้ซื้อที่กำลังเปรียบเทียบในขั้นตอนตัดสินใจสุดท้าย",
    objective: "ดึงยอดจองจากผู้ซื้อที่กำลังชั่งใจระหว่าง 2-3 แบรนด์",
    content_pillar: "Competitive Comparison",
    platform: "instagram",
    format: "Swipe Carousel (10 Slides)",
    key_message: "PK Sedan X ให้ฟังก์ชันความปลอดภัยครบตั้งแต่รุ่นเริ่มต้น ไม่ต้องจ่ายเพิ่ม",
    cta: "เซฟโพสต์นี้ไว้เปิดเทียบตอนไปดูรถจริงที่งานมอเตอร์โชว์",
    reasoning: "กระตุ้นการบันทึก (Save Rate) และเป็นคู่มือช่วยตัดสินใจหน้างาน",
    priority: "HIGH",
    funnel_stage: "BOFU",
    status: "APPROVED",
    created_at: "2026-09-05T08:00:00Z",
    updated_at: "2026-09-05T08:00:00Z",
  }
];
export const ADDITIONAL_DEMO_IDEAS: ContentIdea[] = [
  {
    id: "idea-006",
    campaign_id: "camp-003",
    title: "[DEMO] แบตไฮบริดลูกละแสนจริงไหม? เผยต้นทุนบำรุงรักษา 5 ปี",
    concept: "เปิดตารางค่าใช้จ่ายเช็กระยะจริง พร้อมการรับประกัน 8 ปี",
    hook: "กลัวซื้อไฮบริดแล้วค่าซ่อมแพง? นี่คือใบเสร็จจริงตลอด 5 ปีแรก",
    target_audience: "คนที่ลังเลจะเปลี่ยนจากเครื่องสันดาปเดิมมาใช้ไฮบริด",
    objective: "แก้ความเชื่อผิดๆ (Myth Busting) เกี่ยวกับค่าดูแลรถไฮบริด",
    content_pillar: "Myth Busting & Maintenance",
    platform: "facebook",
    format: "Long-form Post + Infographic",
    key_message: "รับประกันแบต 8 ปี ฟรีค่าแรงเช็กระยะ 5 ปี ค่าบำรุงรักษาเฉลี่ยเท่ารถน้ำมันเดิม",
    cta: "นัดหมายทดลองขับพร้อมรับแพ็กเกจบำรุงรักษาฟรี 5 ปีทันที",
    reasoning: "แก้ปัญหาข้อกังขาเรื่องค่าซ่อม",
    priority: "MEDIUM",
    funnel_stage: "MOFU",
    status: "IDEA",
    created_at: "2026-09-05T09:00:00Z",
    updated_at: "2026-09-05T09:00:00Z",
  },
  {
    id: "idea-007",
    campaign_id: "camp-001",
    title: "[DEMO] 5 เคล็ดลับขับ PK Sedan X ให้แตะ 28 กม./ลิตร",
    concept: "ทริคการขับขี่แบบ Eco-Driving ดึงประสิทธิภาพมอเตอร์ไฟฟ้าสูงสุด",
    hook: "ไม่อยากเปลืองน้ำมันแม้แต่นิดเดียว? แค่ปรับพฤติกรรม 5 ข้อนี้",
    target_audience: "เจ้าของรถปัจจุบันและผู้ที่กำลังสนใจซื้อรถประหยัดพลังงาน",
    objective: "สร้างคุณค่าและ Community การแบ่งปันเทคนิคการขับขี่",
    content_pillar: "Tips & How-To",
    platform: "tiktok",
    format: "Shorts / Reels 30s",
    key_message: "ขับสมูท ใช้ระบบ Regenerative Braking ให้เป็น ประหยัดขึ้น 20%",
    cta: "ลองเอาไปทำตามแล้วมาคอมเมนต์บอกผลลัพธ์กันนะ",
    reasoning: "คอนเทนต์แนวแนะแนวเคล็ดลับมี Engagement และการแชร์สูง",
    priority: "MEDIUM",
    funnel_stage: "TOFU",
    status: "IDEA",
    created_at: "2026-09-05T09:10:00Z",
    updated_at: "2026-09-05T09:10:00Z",
  },
  {
    id: "idea-008",
    campaign_id: "camp-005",
    title: "[DEMO] ทำไมผู้บริหารยุคใหม่ถึงเลือก Fleet รถยนต์พลังงานทางเลือก?",
    concept: "บทวิเคราะห์ ESG และการลดหย่อนภาษี 2 เท่าสำหรับรถประจำตำแหน่ง",
    hook: "ลดต้นทุนองค์กร 24% พร้อมตอบโจทย์เป้าหมาย Net Zero ของบริษัทได้อย่างไร?",
    target_audience: "C-Level, Finance Director และเจ้าของกิจการ",
    objective: "สร้าง Leads ฝ่าย Fleet และขยายลูกค้านิติบุคคล",
    content_pillar: "Corporate & B2B Strategy",
    platform: "linkedin",
    format: "Thought Leadership Article",
    key_message: "PK Fleet ช่วยให้องค์กรบริหาร Total Cost of Ownership ต่ำที่สุด",
    cta: "ติดต่อทีมผู้เชี่ยวชาญเพื่อรับโปรแกรมคำนวณ TCO สิทธิพิเศษสำหรับนิติบุคคล",
    reasoning: "เจาะกลุ่มกำลังซื้อสูงและยอดสั่งซื้อแบบ Volume ล็อตใหญ่",
    priority: "HIGH",
    funnel_stage: "BOFU",
    status: "IDEA",
    created_at: "2026-09-05T09:20:00Z",
    updated_at: "2026-09-05T09:20:00Z",
  },
  {
    id: "idea-009",
    campaign_id: "camp-001",
    title: "[DEMO] เสียงห้องโดยสารเงียบแค่ไหน? ทดสอบวัดระดับเดซิเบลที่ความเร็ว 120",
    concept: "การทดสอบวิทยาศาสตร์ด้วยเครื่องวัดเสียง dB meter บนทางด่วน",
    hook: "รถหรูหลักล้าน ต้องเงียบขนาดไหน? มาดูผลวัดเสียงสดๆ ที่ 120 กม./ชม.",
    target_audience: "ผู้ซื้อที่เน้นความหรูหรา ความเงียบ และสุนทรียภาพในการเดินทาง",
    objective: "พิสูจน์ฉนวนกันเสียง Double Acoustic Glass ของ PK Sedan X",
    content_pillar: "Premium Engineering",
    platform: "youtube",
    format: "ASMR / Review Clip 3 mins",
    key_message: "ห้องโดยสารเงียบสนิทด้วยกระจกซับเสียงรอบคัน",
    cta: "สัมผัสความเงียบด้วยหูของคุณเองที่งาน Exclusive Test Drive สุดสัปดาห์นี้",
    reasoning: "มอบคุณค่าความรู้สึกพรีเมียมที่เหนือกว่าคู่แข่งในระดับราคาเดียวกัน",
    priority: "HIGH",
    funnel_stage: "MOFU",
    status: "IDEA",
    created_at: "2026-09-05T09:30:00Z",
    updated_at: "2026-09-05T09:30:00Z",
  },
  {
    id: "idea-010",
    campaign_id: "camp-001",
    title: "[DEMO] แวะชาร์จมือถือไร้สาย หรือเชื่อมต่อ Apple CarPlay ใน 3 วิ",
    concept: "Short aesthetic clip โชว์ความ Smooth ของระบบ Cabin Tech",
    hook: "เบื่อไหมกับสายระโยงระยางในรถ? แค่วางก็ติด ขึ้นรถก็ต่อเลย",
    target_audience: "Gen Z & Millennial Tech-Savvy",
    objective: "สร้างความประทับใจใน UI และความสะดวกสบายในรถยนต์",
    content_pillar: "Tech Lifestyle",
    platform: "instagram",
    format: "Reels Aesthetic 15s",
    key_message: "ความสะดวกที่ออกแบบมาเพื่อชีวิตที่ไม่หยุดนิ่ง เชื่อมต่อไร้รอยต่อ",
    cta: "แตะลิงก์ใน Bio เพื่อดูดีไซน์ภายในแบบ 360 องศา",
    reasoning: "คลิปสั้น Aesthetic เน้นเพลงเท่ๆ ดึงดูดกลุ่มคนรุ่นใหม่อย่างรวดเร็ว",
    priority: "LOW",
    funnel_stage: "TOFU",
    status: "IDEA",
    created_at: "2026-09-05T09:40:00Z",
    updated_at: "2026-09-05T09:40:00Z",
  },
  {
    id: "idea-011",
    campaign_id: "camp-004",
    title: "[DEMO] ขับลุยฝนหนัก น้ำท่วมรอระบาย PK Sedan X ลุยได้สูงแค่ไหน?",
    concept: "คำแนะนำทางเทคนิคเรื่อง Ground Clearance และระบบซีลกันน้ำของระบบไฟฟ้า",
    hook: "ฝนตก น้ำท่วมกรุง ขับรถไฮบริดจะปลอดภัยไหม? สเปกจริงบอกไว้ชัดเจน",
    target_audience: "ผู้ขับขี่ในเมืองที่กังวลเรื่องน้ำท่วมขังช่วงหน้าฝน",
    objective: "คลายความวิตกเรื่องระบบไฟฟ้ากับน้ำท่วมตามมาตรฐาน IP67",
    content_pillar: "Safety & Reliability",
    platform: "facebook",
    format: "Photo Set + Safety Guide",
    key_message: "แบตเตอรี่มาตรฐานกันน้ำ IP67 ขับผ่านน้ำขังได้อย่างมั่นใจและปลอดภัย",
    cta: "แชร์เก็บไว้เพื่อความปลอดภัยของเพื่อนร่วมทาง",
    reasoning: "คอนเทนต์ทันสถานการณ์ มีผู้ติดตามสูงช่วงหน้าฝน",
    priority: "HIGH",
    funnel_stage: "MOFU",
    status: "IDEA",
    created_at: "2026-09-05T09:50:00Z",
    updated_at: "2026-09-05T09:50:00Z",
  },
  {
    id: "idea-012",
    campaign_id: "camp-001",
    title: "[DEMO] พ่อแม่ยุคใหม่วาง Car Seat ตรงไหนสะดวกสุดใน PK Sedan X?",
    concept: "รีวิวฟังก์ชัน ISOFIX และพื้นที่วางขาเบาะหลังสำหรับคุณแม่และลูกน้อย",
    hook: "มองหารถครอบครัวคันแรก? มาดูมุมที่คุณแม่ตัวจริงให้คะแนนเต็มสิบ",
    target_audience: "ครอบครัวที่มีลูกเล็ก (Young Family)",
    objective: "ขยายกลุ่มลูกค้าจากหนุ่มสาวโสดสู่กลุ่มครอบครัวเริ่มต้น",
    content_pillar: "Family Comfort",
    platform: "facebook",
    format: "Review Album 6 Photos",
    key_message: "กว้างขวาง ปลอดภัย ติดตั้ง Car Seat ง่าย พร้อมช่องแอร์หลังแยกอิสระ",
    cta: "พาครอบครัวมาทดลองนั่งจริงได้ที่โชว์รูม PK Auto ทุกสาขา",
    reasoning: "กลุ่มครอบครัวเป็นผู้ตัดสินใจซื้อที่มีกำลังทรัพย์",
    priority: "MEDIUM",
    funnel_stage: "BOFU",
    status: "IDEA",
    created_at: "2026-09-05T10:00:00Z",
    updated_at: "2026-09-05T10:00:00Z",
  },
  {
    id: "idea-013",
    campaign_id: "camp-001",
    title: "[DEMO] 3 เหตุผลที่ทำให้ห้องโดยสาร PK Sedan X ได้รางวัล Best Interior",
    concept: "ภาพมุมสูงและ Material Close-up ของเบาะหนัง Nappa และลายไม้ธรรมชาติ",
    hook: "ความหรูหราที่คุณสัมผัสได้ทุกวัน ไม่ต้องจ่ายในราคา 2 ล้าน",
    target_audience: "คนที่ชื่นชอบงานดีไซน์ วัสดุพรีเมียม และความประณีต",
    objective: "ยกระดับภาพลักษณ์แบรนด์ (Brand Elevation)",
    content_pillar: "Design & Craftsmanship",
    platform: "instagram",
    format: "Carousel Album 5 Slides",
    key_message: "ความประณีตในทุกรายละเอียด เบาะนั่งสรีรศาสตร์พร้อมฟังก์ชันระบายอากาศ",
    cta: "คลิกเพื่อชม Gallery ห้องโดยสารความละเอียดสูง",
    reasoning: "ภาพที่สวยงามสะท้อนความหรูหราช่วยดึงดูดกลุ่มผู้ซื้อ",
    priority: "LOW",
    funnel_stage: "TOFU",
    status: "IDEA",
    created_at: "2026-09-05T10:10:00Z",
    updated_at: "2026-09-05T10:10:00Z",
  },
  {
    id: "idea-014",
    campaign_id: "camp-002",
    title: "[DEMO] จาก 0 ถึง 80% ใน 22 นาที! ชาร์จไวเหมือนแวะจิบกาแฟ",
    concept: "Time-lapse ระหว่างแวะพักเข้าห้องน้ำจิบกาแฟที่สถานีชาร์จ",
    hook: "คนยังดื่มกาแฟไม่ทันหมดแก้ว... แบตรถก็พร้อมวิ่งต่ออีก 400 กิโลเมตรแล้ว!",
    target_audience: "ผู้ใช้รถยนต์ไฟฟ้าที่ต้องการความรวดเร็วในการเดินทางข้ามจังหวัด",
    objective: "แก้ปัญหาเรื่องระยะเวลาในการชาร์จ (Charging Anxiety)",
    content_pillar: "EV Practicality",
    platform: "tiktok",
    format: "Time-lapse Video 30s",
    key_message: "สถาปัตยกรรม 800V ชาร์จไวระดับแถวหน้า เดินทางไกลไม่ต้องรอนาน",
    cta: "เช็กสถานีชาร์จ Ultra Fast Charge ทั่วไทยผ่านแอป PK Connect",
    reasoning: "ภาพจริงของการดื่มกาแฟช่วยให้เห็นมิติของเวลาที่สั้นลง",
    priority: "HIGH",
    funnel_stage: "MOFU",
    status: "IDEA",
    created_at: "2026-09-05T10:20:00Z",
    updated_at: "2026-09-05T10:20:00Z",
  },
  {
    id: "idea-015",
    campaign_id: "camp-001",
    title: "[DEMO] บทสรุป 1 เดือนแรกกับ PK Sedan X: คุ้มค่าจริงไหม หรือแค่กระแส?",
    concept: "Real Owner 1-Month Follow-Up สรุปข้อดีและสิ่งที่อยากให้ปรับปรุงอย่างตรงไปตรงมา",
    hook: "ขับมาครบ 3,000 กิโลเมตรแรก... นี่คือความจริงทั้งหมดแบบไม่มีสปอนเซอร์ปิดบัง",
    target_audience: "ผู้ที่กำลังหาข้อมูลและอ่านรีวิวผู้ใช้จริง",
    objective: "สร้างความไว้วางใจสูงสุดในขั้นตอนตัดสินใจขั้นสุดท้าย",
    content_pillar: "Authentic User Experience",
    platform: "facebook",
    format: "In-depth User Article",
    key_message: "รถยนต์ที่คุ้มค่าและตอบโจทย์วิถีชีวิตคนเมืองอย่างแท้จริง",
    cta: "พร้อมสัมผัสประสบการณ์จริงหรือยัง? ลงทะเบียนรับสิทธิ์ทดลองขับพิเศษ",
    reasoning: "ความจริงใจในการพูดถึงจุดเด่นและข้อแนะนำสร้าง Conversion ปิดการขายได้ดีที่สุด",
    priority: "HIGH",
    funnel_stage: "BOFU",
    status: "IDEA",
    created_at: "2026-09-05T10:30:00Z",
    updated_at: "2026-09-05T10:30:00Z",
  }
];

export const ALL_DEMO_IDEAS = [...DEMO_IDEAS, ...ADDITIONAL_DEMO_IDEAS];
